const asar = require('@electron/asar')
const pkg = asar.listPackage('dist/win-unpacked/resources/app.asar')
const norm = (s) => s.replace(/\\/g, '/')
const has = (s) => pkg.some((f) => norm(f).includes(s))
console.log('内置样例 water_meter.csv:', has('resources/meter-data/water_meter.csv') ? 'OK' : 'MISSING!')
console.log('内置样例 power_meter.csv:', has('resources/meter-data/power_meter.csv') ? 'OK' : 'MISSING!')
console.log('iconv-lite:', has('node_modules/iconv-lite/package.json') ? 'OK' : 'MISSING!')
console.log('主进程入口:', has('out/main/index.js') ? 'OK' : 'MISSING!')
console.log('渲染进程:', has('out/renderer/index.html') ? 'OK' : 'MISSING!')